### ISSUE TITLE
Poodle does not kill downward process when stopped by KeyboardInterrupt

### ISSUE THREAD

**Issue by grandrew** [criticalhop/poodle#161]
How to reproduce:

1. In local run mode, start solving a big task
2. hit CTRL-C while it is working in translate or downward phase
3. depending on when you hit ctrl-c, you will be left with different zombie processes

- [ ] create unit test to reproduce
- [ ] create handler, see how web_solver.py kills it
- [ ] make sure to kill it in all phases:
    - [ ] poodle generation of PDDL
    - [ ] translation of PDDL into SAS file
    - [ ] search phase in "downward" C++ binary

**Comment by makarty** [comment]
tested branch develop--nozombie
